name: empirepos

description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_cupertino_date_picker_fork: ^1.0.7
  bitsdojo_window: ^0.1.6
  desktop_window: ^0.4.0
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  money_formatter: ^0.0.6
  msix: ^3.16.7
  image_picker: ^1.1.2
  file_selector: ^1.0.3
  file_selector_windows: ^0.9.3+1
  provider: ^6.1.2
  file_picker: ^8.0.5
  image_cropper: ^7.1.0
  native_image_cropper: ^0.6.0
  native_image: ^1.0.2
  image: ^4.2.0
  hive: ^2.2.3
  flutter_slidable: ^3.1.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

